spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commentaire
    username: postgres
    password: Omayma
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8062

